routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home.welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\Home\HomeController::class, 'index'])->name('home');

Route::resource('home_histories', App\Http\Controllers\Home\HistoryController::class);
Route::resource('admin_histories', App\Http\Controllers\Admin\HistoryController::class);
Route::resource('admin', App\Http\Controllers\Admin\AdminController::class)->middleware('admin');

app/Models/History.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class History extends Model
{
    protected $fillable = [
    	'title', 'description', 'user_id'
    ];

    public function user() {
    	
    	//История принаджежит пользователю
    	return $this->belongsTo(User::class);

    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function histories(){
        return $this->hasMany(History::class);
    }

}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function index(){
    	return redirect()->route('admin_histories.index');
    }
}

app/Http/Controllers/Admin/HistoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\History;
use App\Http\Requests\HistoryRequest;

class HistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $histories = History::all();
        return view('admin.home', compact('histories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HistoryRequest $request)
    {
        History::create($request->all());

        return redirect()->route('admin_histories.index')
                            ->with('success', 'History added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(History $admin_history)
    {
        return view('admin.show', compact('admin_history'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(History $admin_history)
    {
        return view('admin.edit', compact('admin_history'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HistoryRequest $request, History $admin_history)
    {
        $admin_history->update($request->all());
        return redirect()->route('admin_histories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(History $admin_history)
    {
        $admin_history->delete();
        return redirect()->route('admin_histories.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Home/HistoryController.php
<?php

namespace App\Http\Controllers\Home;

use App\Models\History;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\HistoryRequest;
use Auth;

class HistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if ((Auth::user() -> is_admin) == 1) {
            $histories = History::all();
        } else {
            $user_id = Auth::user() -> id;
            $results = History::with(['user']) -> where('user_id', $user_id);
            $histories = $results -> get();
        }
        return view('home.home', compact('histories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('home.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HistoryRequest $request)
    {
        History::create($request->all());

        return redirect()->route('home_histories.index')
                            ->with('success', 'History added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(History $home_history)
    {
        return view('home.show', compact('home_history'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(History $home_history)
    {
        return view('home.edit', compact('home_history'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(HistoryRequest $request, History $home_history)
    {
        $home_history->update($request->all());
        return redirect()->route('home_histories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(History $home_history)
    {
        $home_history->delete();
        return redirect()->route('home_histories.index');
    }
}

app/Http/Controllers/Home/HomeController.php
<?php

namespace App\Http\Controllers\Home;

use App\Models\History;
use Illuminate\Http\Request;
use App\Http\Requests\HistoryRequest;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect()->route('home_histories.index');
    }


}

resources/views/admin/create.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <h3>Add History</h3>
    <form action="{{ route('admin_histories.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-12">

                 <div class="form-group">
                    <label>Title</label>
                    <input value="{{ old('title') }}" 
                         type="text" class="form-control" name='title'>
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <label>Description</label>
                    <textarea
                        type="text" name="description" class="form-control">{{ old('description') }}</textarea>
                    @error('description')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <input value="{{ Auth::user()->id }}" 
                         type="hidden" class="form-control" name='user_id'>
                    <br>
                    <button class="btn btn-success">Submit</button>
                 </div>

            </div>
        </div>
    </form>
</div>

@endsection

resources/views/admin/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <h3>Update History</h3>
    <form method="POST" action="{{ route('admin_histories.update', $admin_history) }}">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-md-12">

                 <div class="form-group">
                    <input value="{{ old('title', $admin_history->title) }}" 
                        type="text" name='title' class="form-control">
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <textarea 
                        type="text" name="description" class="form-control">{{ old('description', $admin_history->description) }}</textarea>
                    @error('description')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <button class="btn btn-success">Submit</button>
                 </div>

            </div>
        </div>
    </form>
</div>

@endsection

resources/views/admin/home.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <h3 class="mt-2">Histories</h3>
    <a href="{{ route('admin_histories.create') }}" class="btn btn-success mb-2">Create</a>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table">
                <thead>

                    <tr>
                        <th>ID</th>
                        <th>title</th>
                        <th style="width: 30%; word-break:break-all; word-wrap:break-word;">description</th>
                        <th>user name</th>
                    </tr>

                </thead>

                <tbody>
                 @foreach($histories as $history)
                    <tr>
                        <td>{{ $history -> id }}</td>
                        <td>{{ $history -> title }}</td>
                        <td style="width: 30%; word-break:break-all; word-wrap:break-word;">{{ $history -> description }}</td>
                        <td>{{ $history -> user -> name }}</td>
                        <td>
                            <a type="button" href="{{ route('admin_histories.edit', $history) }}">Edit</a>
                        </td>
                        <td>
                            <a type="button" href="{{ route('admin_histories.show', $history) }}">Show</a>
                        </td>
                        <td>
                            <form method="POST" action="{{ route('admin_histories.destroy', $history) }}">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                 @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@endsection('content')

resources/views/admin/show.blade.php
@extends('layouts.master')

@section('content')

<a type="button" class="btn btn-secondary" href="{{ route('admin_histories.index') }}">Back to histories</a>
<div class="card m-auto" style="width: 18rem;">
	<ul class="list-group list-group-flush">
		<li class="list-group-item">ID: {{ $admin_history->id }}</li>
		<li class="list-group-item">Title: {{ $admin_history->title }}</li>
		<li class="list-group-item">Description: {{ $admin_history->description }}</li>
		<li class="list-group-item">User name: {{ $admin_history-> user -> name }}</li>
		<li class="list-group-item">Created at: {{ $admin_history->created_at }}</li>
		<li class="list-group-item">Updated at: {{ $admin_history->updated_at }}</li>
	</ul>
</div>

@endsection

resources/views/home/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h3>Add History</h3>
    <form action="{{ route('home_histories.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-12">

                 <div class="form-group">
                    <label>Title</label>
                    <input value="{{ old('title') }}" 
                         type="text" class="form-control" name='title'>
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <label>Description</label>
                    <textarea
                        type="text" name="description" class="form-control">{{ old('description') }}</textarea>
                    @error('description')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <input value="{{ Auth::user()->id }}" 
                         type="hidden" class="form-control" name='user_id'>
                    <br>
                    <button class="btn btn-success">Submit</button>
                 </div>

            </div>
        </div>
    </form>
</div>

@endsection

resources/views/home/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h3>Update History</h3>
    <form method="POST" action="{{ route('home_histories.update', $home_history) }}">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-md-12">

                 <div class="form-group">
                    <input value="{{ old('title', $home_history->title) }}" 
                        type="text" name='title' class="form-control">
                    @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <textarea 
                        type="text" name="description" class="form-control">{{ old('description', $home_history->description) }}</textarea>
                    @error('description')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                    <br>
                    <button class="btn btn-success">Submit</button>
                 </div>

            </div>
        </div>
    </form>
</div>

@endsection

resources/views/home/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
            <div class="container">

                @if ((Auth::user() -> is_admin) == 1) 

                <div class="row">
                    <button type="button" class="btn btn-primary mt-2 ml-auto mr-auto"><a href="{{ route('admin.index') }}" style="color: white;">Go to admin panel</a></button>
                </div>

                @endif

                <div class="container">
                    <h3 class="mt-2">Histories</h3>
                    <a href="{{ route('home_histories.create') }}" class="btn btn-success mb-2">Create</a>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <table class="table">
                                <thead>

                                    <tr>
                                        <th>ID</th>
                                        <th>title</th>
                                        <th style="width: 30%; word-break:break-all; word-wrap:break-word;">description</th>
                                        <th>user name</th>
                                    </tr>

                                </thead>

                                <tbody>
                                 @foreach($histories as $history)
                                    <tr>
                                        <td>{{ $history -> id }}</td>
                                        <td>{{ $history -> title }}</td>
                                        <td style="width: 30%; word-break:break-all; word-wrap:break-word;">{{ $history -> description }}</td>
                                        <td>{{ $history -> user -> name }}</td>
                                        <td>
                                            <a type="button" href="{{ route('home_histories.edit', $history) }}">Edit</a>
                                        </td>
                                        <td>
                                            <a type="button" href="{{ route('home_histories.show', $history) }}">Show</a>
                                        </td>
                                        <td>
                                            <form method="POST" action="{{ route('home_histories.destroy', $history) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                 @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home/show.blade.php
@extends('layouts.app')

@section('content')

<a type="button" class="btn btn-secondary" href="{{ route('home_histories.index') }}">Back to histories</a>
<div class="card m-auto" style="width: 18rem;">
	<ul class="list-group list-group-flush">
		<li class="list-group-item">ID: {{ $home_history->id }}</li>
		<li class="list-group-item">Title: {{ $home_history->title }}</li>
		<li class="list-group-item">Description: {{ $home_history->description }}</li>
		<li class="list-group-item">User name: {{ $home_history-> user -> name }}</li>
		<li class="list-group-item">Created at: {{ $home_history->created_at }}</li>
		<li class="list-group-item">Updated at: {{ $home_history->updated_at }}</li>
	</ul>
</div>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/authentication.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" href="{{ asset('assets/images/favicon.ico') }}" type="image/x-icon"> <!-- Favicon-->
    <title>@yield('title') - {{ config('app.name') }}</title>
    <meta name="description" content="@yield('meta_description', config('app.name'))">
    <meta name="author" content="@yield('meta_author', config('app.name'))">
    @yield('meta')

    @stack('before-styles')
    <link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/animate-css/vivify.min.css') }}">
    @stack('after-styles')

    @if (trim($__env->yieldContent('page-styles')))    
        @yield('page-styles')
    @endif    
    <!-- Custom Css -->
    <link rel="stylesheet" href="{{ asset('assets/css/mooli.min.css') }}">
</head>

<body class="theme-cyan">

<div class="auth-main">

    <div class="auth_div vivify fadeIn">
        @yield('content')

        <div class="animate_lines">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </div>
    
</div>

<!-- Scripts -->
@stack('before-scripts')
<script src="{{ asset('assets/bundles/libscripts.bundle.js') }}"></script>
<script src="{{ asset('assets/bundles/vendorscripts.bundle.js') }}"></script>
@stack('after-scripts')

@if (trim($__env->yieldContent('page-script')))
    @yield('page-script')
@endif
    
</body>
</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta name="csrf-token" content="{{ csrf_token() }}">
<link rel="icon" href="{{ asset('assets/images/favicon.ico') }}" type="image/x-icon"> <!-- Favicon-->
<title>@yield('title') - {{ config('app.name') }}</title>
<meta name="description" content="@yield('meta_description', config('app.name'))">
<meta name="author" content="@yield('meta_author', config('app.name'))">

@yield('meta')
@stack('before-styles')
<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}">    
<link rel="stylesheet" href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}">    
<link rel="stylesheet" href="{{ asset('assets/vendor/animate-css/vivify.min.css') }}">

@stack('after-styles')
@if (trim($__env->yieldContent('page-styles')))    
@yield('page-styles')
@endif    

<!-- Custom Css -->
<link rel="stylesheet" href="{{ asset('assets/css/mooli.min.css') }}">
</head>

<body data-theme="light">
    
<div id="body" class="theme-cyan">
    

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>

    <div id="wrapper">
        
        <!-- main page header -->
        @include('layouts.navbar')

        <!-- project main left menubar -->
        @include('layouts.sidebar')

        <!-- Rightbar chat  -->
        @include('layouts.rightbar')    

        <!-- sticky note rightbar div -->
        @include('layouts.stickynote')

        <div id="main-content">
            <div class="container-fluid">          

                @yield('content')

            </div>
        </div>        
    </div>

    @yield('popup')
    
</div>


<!-- main jquery and bootstrap Scripts -->
@stack('before-scripts')
<script src="{{ asset('assets/bundles/libscripts.bundle.js') }}"></script>
<script src="{{ asset('assets/bundles/vendorscripts.bundle.js') }}"></script>
@stack('after-scripts')

<!-- vendor js file -->
@yield('vendor-script')

<!-- project main Scripts js-->
<script src="{{ asset('assets/bundles/mainscripts.bundle.js') }}"></script>

<!-- page Scripts ja -->
@yield('page-script')

<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5e44175da89cda5a188591ec/1e0t1qduj';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

</body>
</html>

resources/views/layouts/rightbar.blade.php
<div id="rightbar" class="rightbar">
    <div class="slim_scroll">
        <div class="chat_list">
            <form>
                <div class="input-group c_input_group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="in-magnifier"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
            </form>
            <div class="body">
                <ul class="nav nav-tabs3 white mt-3 d-flex text-center">
                    <li class="nav-item flex-fill"><a class="nav-link active show" data-toggle="tab" href="#chat-Users">Chat</a></li>
                    <li class="nav-item flex-fill"><a class="nav-link" data-toggle="tab" href="#chat-Groups">Groups</a></li>
                    <li class="nav-item flex-fill"><a class="nav-link mr-0" data-toggle="tab" href="#chat-Contact">Contact</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane vivify fadeIn active show" id="chat-Users">
                        <ul class="right_chat list-unstyled mb-0 animation-li-delay">
                            
                        </ul>
                    </div>
                    <div class="tab-pane vivify fadeIn" id="chat-Groups">
                        <ul class="right_chat list-unstyled mb-0 animation-li-delay">
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/stickynote.blade.php
<div class="sticky-note">
        <a href="javascript:void(0);" class="right_note"><i class="fa fa-close"></i></a>
        <div class="form-group c_form_group">
            <label>Write your note here</label>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Enter here...">
                <div class="input-group-append"><button class="btn btn-dark btn-sm" type="button">Add</button></div>
            </div>
        </div>
        <div class="note-body">
            
        </div>
</div>